### ISSUE TITLE
Merge upstream ?

### ISSUE THREAD

**Issue by offalynne** [amigavision/TopazDouble#3]
@limi is it OK with you if I PR the AmigaVision extra fonts Topaz13 Topaz20 upstream to MiSTer-devel/Fonts_MiSTer ? Can offer credit via filename if you prefer, eg. `Computer_AMIGAVISION-Topaz13`

**Comment by limi** [comment]
I don’t understand what this would do? TopazDouble is a recreation of the Amiga bitmap fonts in Amiga font format, 2× height (8×16px) for use with 1:1 aspect ratio resolutions (e.g. 640×480) instead of the Amiga’s default 640×256/200. They are pixel-for-pixel identical with the original Topaz, which is already in the MiSTer font repository.

**Comment by offalynne** [comment]
Thanks for clarifying, had missed that it was already packed in

**Comment by limi** [comment]
No problem!
